# MIT License Copyright (c) 2021, h1zzz

version: 2.1

jobs:
  build:
    working_directory: ~/repo/cc
    docker:
      - image: golang:1.17.2-alpine3.14

    steps:
      - checkout
      - run: apk add --no-cache openssl
      - run: openssl genrsa -out key.pem 2048
      - run: openssl req -new -x509 -days 3650 -key key.pem -out cert.pem -subj "/C=US/ST= /L= /O= /OU= /CN= /emailAddress= "
      - run: go mod download
      - run: go build -ldflags "-s -w" -o cc
