-- MIT License Copyright (c) 2021, h1zzz


CREATE TABLE `device` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`host` VARCHAR(64) NOT NULL,
	`status` TINYINT NOT NULL,
	`arch` VARCHAR(64) NOT NULL DEFAULT '',
	`os` VARCHAR(64) NOT NULL DEFAULT '',
	`version` VARCHAR(32) NOT NULL DEFAULT '',
	`hostname` VARCHAR(64) NOT NULL DEFAULT '',
	`time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `address` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`device_id` INT NOT NULL,
	`name` VARCHAR(64) NOT NULL,
	`ip` VARCHAR(64) NOT NULL,
	`mac` VARCHAR(32) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `task` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`device_id` INT NOT NULL,
	`type` VARCHAR(32) NOT NULL,
	`task` TEXT NOT NULL,
	`result` TEXT NOT NULL DEFAULT,
	`time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `task_status` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`device_id` INT NOT NULL,
	`task_id` INT NOT NULL,
	`status` TINYINT NOT NULL,
	PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
