# MIT License Copyright (c) 2021, h1zzz

version: "3.9"
services:
  mysql:
    container_name: purewater-mysql
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  cc:
    container_name: purewater-cc
    build: .
    image: purewater-cc
    restart: always
    tty: true
    depends_on:
      - mysql
    environment:
      LISTEN_ADDR: ${LISTEN_ADDR}
      MYSQL_ADDR: ${MYSQL_ADDR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

