# MIT License Copyright (c) 2021, h1zzz

version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql
    networks:
      - backend

  cc:
    container_name: cc
    build: .
    image: cc
    restart: always
    tty: true
    depends_on:
      - mysql
    ports:
      - "443:443"
      - "2222:22"
    environment:
      SSH_ADDR: ${SSH_ADDR}
      SSH_USER: ${SSH_USER} # Admin username
      SSH_PASSWORD: ${SSH_PASSWORD} # Admin user password
      MYSQL_ADDR: ${MYSQL_ADDR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
    network_mode: host
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
