name: Build Agent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --fix-missing git cmake build-essential mingw-w64
        
    - name: Initialize dependencies
      run: |
        git submodule update --init
        
    - name: Build x86/64 (linux)
      run: |
        cd agent
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE="Release" ..
        cmake --build . --target agent
        
    - name: Build x86/64 (windows)
      run: |
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        cd agent
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE="Release" ..
        cmake --build . --target agent
