name: Build Agent for Linux

on:
  push:
  pull_request:
  release:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Initialize dependencies
      run: git submodule update --init
    
    - name: Build Agent
      run: |
        cd agent
        cmake -DCMAKE_BUILD_TYPE="Release" .
        cmake --build . --target agent
